import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from "@/constants/navigation.constant";

const navigationConfigWolooTaskManagement = [
  {
    key: "Woloos_tasks",
    path: "",
    title: "",
    translateKey: "",
    icon: "",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: "iotData",
        path: "/iotData",
        title: "Dashboard",
        icon: "IOTData",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      // {
      //   key: "dashboard_task",
      //   path: "/dashboard_task",
      //   title: "Task Dashboard",
      //   icon: "dashboard_task",
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: [],
      //   subMenu: [],
      // },
      {
        key: "client_setup",
        path: "",
        title: "Client Setup",
        icon: "client_setup",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
          {
            key: "client",
            path: "/client",
            title: "Client",
            icon: "client",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "location",
            path: "/location",
            title: "Location",
            icon: "location",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "block",
            path: "/block",
            title: "Building",
            icon: "building",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "facility",
            path: "/facility",
            title: "Facility",
            icon: "facility",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "cluster",
            path: "/cluster",
            title: "Cluster",
            icon: "cluster",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "shift",
            path: "/shift",
            title: "Shift",
            icon: "shift",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
      {
        key: "user_setup",
        path: "",
        title: "User Setup",
        icon: "user_setup",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
          {
            key: "supervisor",
            path: "/supervisor",
            title: "Supervisor",
            icon: "supervisor",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "janitor",
            path: "/janitor",
            title: "Janitor",
            icon: "janitor",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "facilityManager",
            path: "/facilityManager",
            title: "Facility Manager",
            icon: "facilityManager",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "booth",
            path: "/booth",
            title: "Booths",
            icon: "booth",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ]
      },
      {
        key: "task_setup",
        path: "",
        title: "Task Setup",
        icon: "task_setup",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
          {
            key: "task_template",
            path: "/task_template",
            title: "Task Template",
            icon: "task_template",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "templateMap",
            path: "/templateMap",
            title: "Template Facility Mapping",
            icon: "templateMap",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "task_checklist",
            path: "/task_checklist",
            title: "Task Checklist",
            icon: "task_checklist",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
     
      {
        key: "iotDevice",
        path: "/iotDevice",
        title: "IOT Device",
        icon: "iotDevice",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "orders",
        path: "/orders",
        title: "Orders",
        icon: "orders",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "subscriptionPlans",
        path: "/subscriptionPlans",
        title: "Subscription Plans",
        icon: "subscription_plans",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "subscriptionSetting",
        path: "/subscriptionSetting",
        title: "Subscription Setting",
        icon: "subscription_settings",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
          {
            key: "plan",
            path: "/plan",
            title: "Plans",
            icon: "plans",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "addon",
            path: "/addon",
            title: "Add on",
            // translateKey: "nav.setting.general",
            icon: "addons",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
      {
        key: "rbac",
        path: "/rbac",
        title: "Roles",
        // translateKey: "nav.voucher",
        icon: "roles",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      // {
      //   key: "reviewManagement",
      //   path: "/reviewManagement",
      //   title: "Review Management",
      //   // translateKey: "nav.voucher",
      //   icon: "reviewManagement",
      //   type: NAV_ITEM_TYPE_ITEM,
      //   authority: [],
      //   subMenu: [],
      // }
    ],
  },
];

export default navigationConfigWolooTaskManagement;
