import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from "@/constants/navigation.constant";

const navigationConfigWolooDiscovery = [
  {
    key: "Woloos",
    path: "",
    title: "",
    translateKey: "",
    icon: "",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: "managment",
        path: "",
        title: "Management",
        // translateKey: "nav.management",
        icon: "woloo",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
          {
            key: "woloos",
            path: "/woloos",
            title: "Woloo Host",
            translateKey: "nav.woloos",
            icon: "woloo",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "users",
            path: "/users",
            title: "Woloo Guest",
            translateKey: "nav.users",
            icon: "users",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "corporates",
            path: "/corporates",
            title: "Corporates",
            translateKey: "nav.corporates",
            icon: "corporates",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "subscription",
            path: "/subscription",
            title: "Subscription",
            translateKey: "nav.subscription",
            icon: "subscription",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "voucher",
            path: "/voucher",
            title: "Voucher Codes",
            translateKey: "nav.voucher",
            icon: "voucher",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "franchise",
            path: "/franchise",
            title: "Franchise",
            // translateKey: "nav.home",
            icon: "franchise",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
      {
        key: "setting",
        path: "/setting",
        title: "Setting",
        icon: "setting",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
          {
            key: "admin",
            path: "/admin",
            title: "Admin",
            icon: "admin",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "general",
            path: "/general",
            title: "General",
            // translateKey: "nav.setting.general",
            icon: "general",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "site",
            path: "/site",
            title: "Site",
            // translateKey: "nav.setting.site",
            icon: "site",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "review",
            path: "/review",
            title: "Review",
            // translateKey: "nav.setting.review",
            icon: "review",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
      {
        key: "transaction",
        path: "/transaction",
        title: "Transaction",
        // translateKey: "nav.voucher",
        icon: "transaction",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "report",
        path: "/reports",
        title: "Reports",
        icon: "report",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
          {
            key: "userReport",
            path: "/userReport",
            title: "User Referral and Subscription ",
            icon: "userReferral",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "subscriptionReport",
            path: "/subscriptionReport",
            title: "Subscription Transaction",
            icon: "subscriptionTransaction",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          // {
          //   key: "voucherReport",
          //   path: "/voucherReport",
          //   title: "Voucher Report",

          //   icon: "",
          //   type: NAV_ITEM_TYPE_ITEM,
          //   authority: [],
          //   subMenu: [],
          // },
          {
            key: "referrerReport",
            path: "/referrerReport",
            title: "Referrer",
            icon: "referrer",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "referrerHistoryReport",
            path: "/referrerHistoryReport",
            title: "Referrer / User History ",
            icon: "userHistory",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "customerHistory",
            path: "/loyaltyReport",
            title: "Loyalty",
            icon: "loyalty",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
      {
        key: "wolooRating",
        path: "/wolooRating",
        title: "Woloo Rating",
        // translateKey: "nav.voucher",
        icon: "wolooRating",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "offer",
        path: "",
        title: "Offers",
        // translateKey: "nav.voucher",
        icon: "hostOffer",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
          {
            key: "hostOffer",
            path: "/hostOffer",
            title: "Woloo Host Offer",
            // translateKey: "nav.voucher",
            icon: "hostOffer",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "userOffer",
            path: "/userOffer",
            title: "User Offer",
            // translateKey: "nav.voucher",
            icon: "userOffer",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
        ],
      },
      {
        key: "activeBlogs",
        path: "",
        title: "Blogs",
        // translateKey: "nav.voucher",
        icon: "activeBlogs",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [
          {
            key: "activeBlogs",
            path: "/activeBlogs",
            title: "Active Blogs",
            // translateKey: "nav.voucher",
            icon: "activeBlogs",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "blogCategory",
            path: "/blogCategory",
            title: "Blog Category",
            // translateKey: "nav.voucher",
            icon: "blogCategory",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          },
          {
            key: "blogSubCategory",
            path: "/blogSubCategory",
            title: "Blog Sub-Category",
            // translateKey: "nav.voucher",
            icon: "blogSubCategory",
            type: NAV_ITEM_TYPE_ITEM,
            authority: [],
            subMenu: [],
          }
        ],
      },
    ],
  },
];
export default navigationConfigWolooDiscovery;