import React from "react";
import HighchartsReact from "highcharts-react-official";
import Highcharts from "highcharts";

const AlertsByTimeGraph = () => {
    const dummyData = [
        { time: "Morning Peak", alerts: 5 },
        { time: "Afternoon Peak", alerts: 8 },
        { time: "Evening Peak", alerts: 3 },
        { time: "Late Night", alerts: 2 },
    ];

    const options = {
        chart: {
            type: "column",
            backgroundColor: "transparent",
        },
        title: {
            text: "Number of Alerts Generated by Time of Day",
            style: {
                fontSize: "16px",
                fontWeight: "bold",
                color: "#717171",
            },
        },
        legend: {
            enabled: false, // No need for a legend since there's only one series
        },
        xAxis: {
            categories: dummyData.map((item) => item.time),
            title: {
                text: "Time of Day",
            },
        },
        yAxis: {
            title: { text: "Number of Alerts", style: { color: "#717171" } },
            labels: { style: { color: "#717171" } },
            min: 0,
            max: 10, // Adjust the max value based on your dataset

            // plotLines: [
            //     {
            //         value: 5, // Threshold value
            //         color: "#FF0000", // Red color for the threshold line
            //         dashStyle: "Dash", // Dashed line style
            //         width: 2, // Line width
            //         label: {
            //             text: "Alert Threshold (5 alerts)",
            //             align: "center",
            //             style: { color: "#FF0000", fontWeight: "bold" },
            //         },
            //     },
            // ],
        },
        series: [
            {
                name: "Number of Alerts",
                data: dummyData.map((item) => item.alerts),
                color: "#717171",
            },
        ],
        exporting: {
            enabled: false, // Disable the hamburger menu
        },
    };

    return (
        <div>
            <div
                style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "20px",
                    marginTop: "20px",
                    padding: "20px",
                    backgroundColor: "#f9f9f9",
                    border: "1px solid #ddd",
                    borderRadius: "8px",
                }}
            >
                <div
                    style={{
                        flex: 1,
                        width: "80%",
                        maxWidth: "800px",
                        backgroundColor: "transparent",
                        marginBottom: "20px",
                    }}
                >
                    <HighchartsReact highcharts={Highcharts} options={options} />
                </div>
                <div
                    style={{
                        flex: 1,
                        fontSize: "14px",
                        color: "#555",
                        padding: "10px",
                        backgroundColor: "#fff",
                        borderRadius: "8px",
                        boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
                    }}
                >
                    <p
                        style={{
                            fontSize: "16px",
                            color: "#333",
                            fontWeight: "bold",
                            marginBottom: "10px",
                        }}
                    >
                        This column graph highlights the number of alerts generated during
                        different times of the day. The metrics are shown as follows:
                    </p>
                    <ul>
                        <li>
                            <strong>Number of Alerts:</strong> Indicates how frequently alerts
                            were generated in each time span.
                        </li>
                        <li>
                            A red threshold line at <strong>5 alerts</strong> serves as a
                            warning indicator.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    );
};

export default AlertsByTimeGraph;
